[meta]
save_dir = "/content/gdrive/MyDrive/Colab Notebooks/FullSubNet"
description = "This is a description of FullSubNet experiment."
seed = 0
use_amp = true
cudnn_enable = true
experiment_name = "train"
config_path = "fullsubnet/train.toml"

[acoustics]
n_fft = 512
win_length = 512
sr = 16000
hop_length = 256

[loss_function]
name = "mse_loss"

[optimizer]
lr = 0.001
beta1 = 0.9
beta2 = 0.999

[train_dataset]
path = "dataset_train.Dataset"

[validation_dataset]
path = "dataset_validation.Dataset"

[model]
path = "model.Model"

[trainer]
path = "trainer.Trainer"

[loss_function.args]

[train_dataset.args]
clean_dataset = "/content/gdrive/MyDrive/Colab Notebooks/FullSubNet/data/clean.txt"
clean_dataset_limit = false
clean_dataset_offset = 0
noise_dataset = "/content/gdrive/MyDrive/Colab Notebooks/FullSubNet/data/noise.txt"
noise_dataset_limit = false
noise_dataset_offset = 0
num_workers = 36
pre_load_clean_dataset = false
pre_load_noise = false
pre_load_rir = false
reverb_proportion = 0.75
rir_dataset = "/content/gdrive/MyDrive/Colab Notebooks/FullSubNet/data/rir.txt"
rir_dataset_limit = false
rir_dataset_offset = 0
silence_length = 0.2
snr_range = [ -5, 20,]
sr = 16000
sub_sample_length = 3.072
target_dB_FS = -25
target_dB_FS_floating_value = 10

[train_dataset.dataloader]
batch_size = 38
num_workers = 12
drop_last = true
pin_memory = true

[validation_dataset.args]
dataset_dir_list = [ "/content/gdrive/MyDrive/Colab Notebooks/FullSubNet/data/test/no_reverb",]
sr = 16000

[model.args]
sb_num_neighbors = 15
fb_num_neighbors = 0
num_freqs = 257
look_ahead = 2
sequence_model = "LSTM"
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2

[trainer.train]
clip_grad_norm_value = 10
epochs = 3
save_checkpoint_interval = 1

[trainer.validation]
save_max_metric_score = true
validation_interval = 1

[trainer.visualization]
metrics = [ "WB_PESQ", "NB_PESQ", "STOI", "SI_SDR",]
n_samples = 10
num_workers = 12
